# Generated by Django 5.1.6 on 2025-02-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('school', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
